### ISSUE TITLE
Create test cases, services, and Controller

### ISSUE THREAD

**Issue by MichelMuemboIlunga** [MichelMuemboIlunga/school_management#10]
In the service package, implement services to consume your repository implementation with
similar operations offered by JPA where appropriate

Code a service to get the employee name given an employee email. Check if the email is valid
and exists.

Implement a service to retrieve all employee name(s) living in a particular city. The formal
parameter passed is the cityId.

NB: Make sure when you send your PR the application.properties db connection string are commented.
And Pulll latest before your push

**Comment by ThatoEmeka** [comment]
100%
